### ISSUE TITLE
两个补充说明

### ISSUE THREAD

**Issue by profthecopyright** [rcy17/signal-system-assignment#1]
我正好是这个专业方向的，看到这个东西就多说几句

1. 这个题目本身的设置其实是有一些瑕疵的，因为题目文档中给出的频率是按照十二平均律调律的（相邻乐音频率间呈公比为2^(1/12）的等比数列）。十二平均律的好处是方便移调，因此广泛被近现代键盘乐器采用；但它的一个重大缺点是所有的音程频率比都不是严格的简单整数比（除了八度的2：1）以外，而是无理数，因此无法再现一些所谓的"完美"和声/和弦（如五度G:C = 3:2被认为是perfect fifth，但平均律只能实现其近似2^(7/12)=1.4983，虽然只差了不到千分之二，但也足以在440 Hz处引入~1 Hz数量级的误差）。这一现象在管弦乐的演奏中尤其明显，因为一些应当完美的和弦可能会产生拍音(beats)，被艺术家认为难以接受，因此直到现在十二平均律仍然不是唯一的调律方式。另一方面就是历史上各种律制不断变迁，十二平均律其实是很近代的事情，在18世纪左右才得到逐渐认可，20世纪才被西方主流音乐界接受。一些古典作品从作曲方式上来讲就不是为十二平均律所作（作曲家会谨慎地避免某些律制中可能产生的wolf interval狼音，即所谓无法忍受的不和谐音程，且不能随意移调，但在某些音程上面讲究极致的和谐），因此如果爱乐乐团在用古老的小提琴演奏古典作品的话，很可能用到的律制并非十二平均律(12-tone equal temperament, 12-TET)，而可能是well temperament, meantone temperament等等（中文我不知道怎么翻译了）。这一点可能是老师的知识准备还不足，但严格来讲如果不用A4而用别的乐音作参照的话，是要考虑到律制不同带来的影响的（如果可以的话建议给老师做个反馈）。

2. 关于report中提到的古人如何区分440和443 Hz的音的问题。首先，人耳的分辨能力在500Hz左右很强，JND（Just-Noticeable Difference）在1Hz左右，也就是说440和441的两个音先后出现的话，一般人是刚好可以听出区别的，对于受良好训练的音乐家甚至专业调音师而言，440和443应该在分辨范围之内。一些具有绝对音准的人甚至可以在没有参照的情况下指出这是440那是443。此外，即使耳朵没有那么好，还有一招可以区分相近的不同音高，也就是前面提到的拍音（beats）。一般来说，在电子时代之前，调音的时候是要用一个标准音叉的，可以固定发出某个频率（如440 Hz）的声音，然后在敲响音叉的同时按下钢琴键（或拨琴弦），如果两者有1 Hz的频率差，那么干涉的结果就会产生1 Hz的AM信号，也就是每秒一次强弱变化的拍。人可以轻易地分出这个拍来，根据拍音消失来确定音准无误。事实上，很多交响乐团中不同乐器之间的调音可能也有细微差别，所以排练的时候一般要试着合奏一下标准音进行校准，否则实际演奏中拍音将难以忍受。

**Comment by rcy17** [comment]
我正好不是这个专业的，我就少说几句。
1. 正如项目名字所说，这是《信号与系统》课程的大作业，不是乐理基础课的大作业。
2. 感谢科普。

**Comment by profthecopyright** [comment]
我的专业是音频信号处理也非乐理 只不过目前在从事音乐相关的研究所以才学习了这些内容 STFT是音频信号处理的基本方法之一 音乐作为音频信号并无特殊之处

我的理解是这门课的老师完全可以选择各种不同的topic作为大作业 但如果老师一定要严肃地把这个音乐相关的题目当作一个研究项目给同学做 那么老师对相关的背景知识就应该进行严谨的调查 确保内容准确 且在作业文档里交代清楚
________________________________

**Comment by profthecopyright** [comment]
抱歉之前从email回复的 刚注意到issue已关闭 打扰请见谅！
________________________________
